# Conclusion

We have some limitations with our data in three aspects and we can take those into accounts for future directions: 
First, we only have 157 students complete the survey with valid amount of answers, which might be relatively small. As the dataset grows larger, we will have more accurate output on some visualizations. 
Second, the fact that only Columbia undergraduate students took the survey might lead to somewhat bias on individual factors such as income or family backgrounds. Third, we have relatively large proportions (~25%) of missing data for columns like father education and mother education, which has weakened our analysis on these two factors by certain degree.

We learnt a lot about data visualization tools and methods from this class. By completing this final project, we even learn more about all the concepts and have gained better insights on how we can use different types of graphs to conduct analysis on real-world data. We also have a better understanding for utilizing D3.js as well as HTML/CSS to produce interactive data visualization on web pages. All in all, it has been great fun to work out graphs and analysis by using different languages such as R, Python and HTML/JavaScript that we learnt from this EDAV class! 
