--- 
title: "Stress Perception Decomposition"
author: "Hongling Liu, Megan Goldring, Xinrui Zhang and Yuxin Zhou"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---
 
# Introduction

In today’s fast-paced modern world, people can easily get stressed out in many different aspects of their lives, and the causes of stress can differ from person to person depending on one’s gender, age or even relationship with a person’s close ones. Therefore, with curiosity of how people perceive and respond to different stressors, we start to conduct visualization analysis on data coming from a stress research and try our best to bring some insights to this important area of study. 

The study that we pulled data from has designed many interesting stress scenarios as vignettes for research participants to respond to. Each vignette can be scored by each participant from not at all to extremely severed in stressfulness. From this collection of data, we can see how people respond to different scenarios as well as how aspects of life make people feel most stressed out. Also, participants are asked to attend two Zoom sessions one week apart to rate different vignette twice. This is also very interesting because we can see how people respond to same stress scenarios when time flies.

In this project, we want to find answers to whether people’s stress level response to different scenarios is aligned with the objective coder ratings of how severe those scenarios are. We also interested in how different contents of scenarios influence people’s stressfulness. In the last, we would also like to show if there are any individual factors such as sex and income may influence their level of stress to different degree.
